name: Claude PR review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  claude-response:
    if: |
      github.event.pull_request.user.login == 'thenets'
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          use_sticky_comment: true
          override_prompt: |
            Analyze PR #$PR_NUMBER in $REPOSITORY for security vulnerabilities.

            Changed files:
            $CHANGED_FILES

            Focus on:
            - SQL injection risks
            - XSS vulnerabilities
            - Authentication bypasses
            - Exposed secrets or credentials

            Provide severity ratings (Critical/High/Medium/Low) for any issues found.